import os
import time
import uuid
from pathlib import Path

from flask import current_app

from .comfy_client import submit_prompt, wait_for_completion, extract_first_image_from_history_item, download_image
from .comfy_workflows import genix_txt2img_workflow


def run_genix(payload: dict, set_progress):
    prompt = payload.get("prompt", "")
    steps = int(payload.get("steps", 25) or 25)
    seed = payload.get("seed")
    if seed is None:
        seed = int(uuid.uuid4().int % 2_000_000_000)

    aspect = (payload.get("aspect_ratio") or "1:1").strip()
    w, h = 512, 512
    if aspect == "16:9":
        w, h = 768, 432
    elif aspect == "9:16":
        w, h = 432, 768
    elif aspect == "4:3":
        w, h = 640, 480
    elif aspect == "3:4":
        w, h = 480, 640

    comfy_url = current_app.config["COMFY_URL"]
    out_dir = current_app.config["GENIX_OUTPUT_DIR"]
    out_prefix = current_app.config["GENIX_OUTPUT_URL_PREFIX"]

    Path(out_dir).mkdir(parents=True, exist_ok=True)

    set_progress(3)
    workflow = genix_txt2img_workflow(prompt=prompt, seed=seed, steps=steps, width=w, height=h)

    prompt_id = submit_prompt(comfy_url, workflow)
    history_item = wait_for_completion(comfy_url, prompt_id, set_progress=set_progress, timeout_s=180.0)

    meta = extract_first_image_from_history_item(history_item)
    if not meta:
        raise RuntimeError("comfy_no_image_output")

    # Download image to our static folder so Flask serves it
    filename = f"genix_{prompt_id}.png"
    save_path = os.path.join(out_dir, filename)
    download_image(comfy_url, meta, save_path)

    set_progress(100)
    return {
        "message": "Generated by ComfyUI (real).",
        "prompt": prompt,
        "seed": seed,
        "steps": steps,
        "width": w,
        "height": h,
        "image_url": f"{out_prefix}/{filename}",
    }
    public = current_app.config.get("PUBLIC_BASE_URL", "")
    url = f"{out_prefix}/{filename}"   # /static/genix/...
    image_url = f"{public}{url}" if public else url

    return {
       "message": "Generated by ComfyUI (real).",
       "prompt": prompt,
       "seed": seed,
       "steps": steps,
       "width": w,
       "height": h,
       "image_url": image_url,
    }


def run_faceswap(payload: dict, set_progress):
    # TODO: replace with InsightFace pipeline
    set_progress(10)
    time.sleep(0.4)
    set_progress(60)
    time.sleep(0.4)
    set_progress(95)
    time.sleep(0.3)

    return {
        "message": "Worker mock face swap complete (wire pipeline next).",
        "output_url": "/static/mock/faceswap_sample.png",
    }
